// src/lib/components/internal/Project.svelte
<script lang="ts">
	export let link: string;
	export let icon: string;
	export let name: string;
	export let color: string;
	export let description: string;
	export let year: string | null;
</script>

<a href={link} class="flex-1 bg-opacity-30 p-4 my-2 rounded-md hover:scale-105 transform ease-in-out duration-300 {color}">
	<div class="flex flex-row items-center">
		<img
          src="{icon.startsWith("http") ? icon : `/img/${icon}`}"
          alt={name}
          class="w-12 h-12 object-contain rounded-md"
        />

		<div class="ml-4 flex flex-col justify-center">
			<h2 class="text-lg font-bold flex items-center">
				{name}
			
				{#if year !== null}
					<span class="text-sm font-normal ml-4 hidden sm:block">[{year}]</span>
				{/if}
			</h2>
			<p class="text-sm">{description}</p>
		</div>
	</div>
</a>

// components/Project.vue
<template>
  <a
    :href="link"
    target="_blank"
    class="flex-1 bg-opacity-30 p-4 my-2 rounded-md hover:scale-105 transform ease-in-out duration-300"
    :class="color"
  >
    <div class="flex flex-row items-center">
      <img
        :src="
          icon
            ? icon.startsWith('https') || icon.startsWith('http')
              ? icon
              : require(`@/assets/img/${icon}`)
            : null
        "
        class="w-12 h-12 object-contain rounded-md"
      />
      <div class="ml-4 flex flex-col justify-center">
        <h2 class="text-lg font-bold flex items-center">
          {{ name }}
          <span v-if="year" class="text-sm font-normal ml-4 hidden sm:block"
            >[{{ year }}]</span
          >
        </h2>
        <p class="text-sm">
          {{ description }}
        </p>
      </div>
    </div>
  </a>
</template>

<script lang="ts">
export default {
  props: {
    icon: {
      type: String,
      default: '',
    },
    name: {
      type: String,
      default: '',
    },
    link: {
      type: String,
      default: '',
    },
    year: {
      type: String,
      default: null,
    },
    description: {
      type: String,
      default: '',
    },
    color: {
      type: String,
      default: 'bg-white',
    },
  },
}
</script>
